apiVersion: v1
kind: Secret
metadata:
    name: jaeger-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:NGtmGGfCbXrG+kM=,iv:3cGp+tH7yOXQaqHWU0txXV5Bl4nvAr6d305Dhe0mP4A=,tag:o2Zz6XBmt7EQ2Lc4AO1CEA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/cf300a49-6d7b-4faa-b63b-e8a48b15e97c
          created_at: "2022-02-10T13:39:14Z"
          enc: AQICAHiQphB+Us6VdiZtldhZXtSe6lZw30l4S67lEwW2+/Zm5QGTdAhQth875fsLTfn92UzIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMu0FhbEj4aIKRzlkMAgEQgDv2DV2zJovv+K6I7izU6jVTC4AhTEmXHhdau8zpv+4qG0yNGX/54Vb8NkBYVd1xEpgKQ91eU/RLJ8//Uw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-10T13:39:14Z"
    mac: ENC[AES256_GCM,data:zHiheColwAYmr5oVqQ1uMichXwim0yZa6NVs7JbRkT9aT17uZ9pGaoot18AMhwL9uDiMoxYh3H2BgEEMgXpNurljP9H8FJKcMdgagQ0WidBIia7kMWb5pPjMQWy58QDyhi68RmDFqqzZN1OaxPPqReMl9hS8G0PCl9Kqhqmf+CQ=,iv:NJz2OMMmbKHvdrHEduheo/Scn1O0rlyvTKwas6+0N5o=,tag:3xJPN6AaqE7yK2nl1bok/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
