apiVersion: v1
kind: Secret
metadata:
    name: kiali-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:YvX3C8nHJsH5RA==,iv:uomAMvDpP+3Bi1FdmrqB8eUU0S1PZhwxZmFxd/kJuNI=,tag:1JxAFiZkFSTwXKNRmomdTg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/cf300a49-6d7b-4faa-b63b-e8a48b15e97c
          created_at: "2022-02-10T13:39:15Z"
          enc: AQICAHiQphB+Us6VdiZtldhZXtSe6lZw30l4S67lEwW2+/Zm5QEETulGHjHh3NklgWnbpRQsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9nJi1v3QsYz9RnxyAgEQgDs16uhDufDiFUwpX6jk38TkSyqvp8LJFDX9hkq0yFwBkBX6ezhQonj0y4jW7eOuMgZ+qwHEnTsLavW+ng==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-10T13:39:15Z"
    mac: ENC[AES256_GCM,data:EL+XGpZXH+f3dYUVdpBrv4E5fL/gixwtIHd18wQo5pvPeoF+VEfsqzlFUz4nze08vg93oiT6VYHA96N+ek5mGtsR/mV8xF5O9CewOrgl2RLORA5owwwlPagYFnmLjF9NAfmAaRXFImeJnnebq2L3ER4nkptCI1YwpFBXE+qSceI=,iv:HjD3xjSX7uKJl7eiTdWVvUF3+f3Px1Z8A5Wp5iAtaWo=,tag:5noIA1JNc/723FHam1ikRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
